/** Declaration file generated by dts-gen */
declare module "prompt" {
    export const allowEmpty: boolean;

    export const colors: boolean;

    export const delimiter: string;

    export const message: string;

    export const paused: boolean;

    export const properties: {
    };

    export const started: boolean;

    export const stopped: boolean;

    export function addListener(type: any, listener: any): any;

    export function addProperties(obj: any, properties: any, callback: any): any;

    export function confirm(...args: any[]): void;

    export function emit(type: any, args: any): any;

    export function eventNames(): any;

    export function get(schema: any, callback: any): any;

    export function getInput(prop: any, callback: any): any;

    export function getMaxListeners(): any;

    export function history(search: any): any;

    export function listenerCount(type: any): any;

    export function listeners(type: any): any;

    export function on(type: any, listener: any): any;

    export function once(type: any, listener: any): any;

    export function pause(): any;

    export function prependListener(type: any, listener: any): any;

    export function prependOnceListener(type: any, listener: any): any;

    export function rawListeners(type: any): any;

    export function removeAllListeners(type: any, ...args: any[]): any;

    export function removeListener(type: any, listener: any): any;

    export function resume(): any;

    export function setMaxListeners(n: any): any;

    export function start(options: any): any;

    export function stop(): any;

    export namespace addListener {
        const prototype: {
        };

    }

    export namespace addProperties {
        const prototype: {
        };

    }

    export namespace confirm {
        const prototype: {
        };

    }

    export namespace emit {
        const prototype: {
        };

    }

    export namespace eventNames {
        const prototype: {
        };

    }

    export namespace get {
        const prototype: {
        };

    }

    export namespace getInput {
        const prototype: {
        };

    }

    export namespace getMaxListeners {
        const prototype: {
        };

    }

    export namespace history {
        const prototype: {
        };

    }

    export namespace listenerCount {
        const prototype: {
        };

    }

    export namespace listeners {
        const prototype: {
        };

    }

    export namespace logger {
        const emitErrs: boolean;

        const exceptionHandlers: {
        };

        const exitOnError: boolean;

        const filters: any[];

        const level: string;

        const levelLength: number;

        const levels: {
            data: number;
            debug: number;
            error: number;
            help: number;
            info: number;
            input: number;
            prompt: number;
            silly: number;
            verbose: number;
            warn: number;
        };

        const padLevels: boolean;

        const profilers: {
        };

        const rewriters: any[];

        const stripColors: boolean;

        const transports: {
            console: {
                addListener: any;
                align: boolean;
                colorize: boolean;
                depth: any;
                emit: any;
                eol: string;
                eventNames: any;
                exceptionsLevel: string;
                formatQuery: any;
                formatResults: any;
                formatter: any;
                getMaxListeners: any;
                handleExceptions: boolean;
                humanReadableUnhandledException: boolean;
                json: boolean;
                label: any;
                level: any;
                listenerCount: any;
                listeners: any;
                log: any;
                logException: any;
                logstash: boolean;
                name: string;
                normalizeQuery: any;
                on: any;
                once: any;
                prependListener: any;
                prependOnceListener: any;
                prettyPrint: boolean;
                raw: boolean;
                rawListeners: any;
                removeAllListeners: any;
                removeListener: any;
                setMaxListeners: any;
                showLevel: boolean;
                silent: boolean;
                stderrLevels: {
                    debug: boolean;
                    error: boolean;
                };
                timestamp: boolean;
            };
        };

        function add(transport: any, options: any, created: any): any;

        function addListener(type: any, listener: any): any;

        function clear(): void;

        function cli(): any;

        function close(): void;

        function configure(options: any): void;

        function data(msg: any, ...args: any[]): void;

        function debug(msg: any, ...args: any[]): void;

        function emit(type: any, args: any): any;

        function error(msg: any, ...args: any[]): void;

        function eventNames(): any;

        function getMaxListeners(): any;

        function handleExceptions(...args: any[]): void;

        function help(msg: any, ...args: any[]): void;

        function info(msg: any, ...args: any[]): void;

        function input(msg: any, ...args: any[]): void;

        function listenerCount(type: any): any;

        function listeners(type: any): any;

        function log(level: any, ...args: any[]): any;

        function on(type: any, listener: any): any;

        function once(type: any, listener: any): any;

        function prependListener(type: any, listener: any): any;

        function prependOnceListener(type: any, listener: any): any;

        function profile(id: any, ...args: any[]): any;

        function prompt(msg: any, ...args: any[]): void;

        function query(options: any, callback: any): any;

        function rawListeners(type: any): any;

        function remove(transport: any): any;

        function removeAllListeners(type: any, ...args: any[]): any;

        function removeListener(type: any, listener: any): any;

        function setLevels(target: any): any;

        function setMaxListeners(n: any): any;

        function silly(msg: any, ...args: any[]): void;

        function startTimer(): any;

        function stream(options: any): any;

        function unhandleExceptions(): void;

        function verbose(msg: any, ...args: any[]): void;

        function warn(msg: any, ...args: any[]): void;

        namespace add {
            const prototype: {
            };

        }

        namespace addListener {
            const prototype: {
            };

        }

        namespace clear {
            const prototype: {
            };

        }

        namespace cli {
            const prototype: {
            };

        }

        namespace close {
            const prototype: {
            };

        }

        namespace configure {
            const prototype: {
            };

        }

        namespace data {
            const prototype: {
            };

        }

        namespace debug {
            const prototype: {
            };

        }

        namespace emit {
            const prototype: {
            };

        }

        namespace error {
            const prototype: {
            };

        }

        namespace eventNames {
            const prototype: {
            };

        }

        namespace getMaxListeners {
            const prototype: {
            };

        }

        namespace handleExceptions {
            const prototype: {
            };

        }

        namespace help {
            const prototype: {
            };

        }

        namespace info {
            const prototype: {
            };

        }

        namespace input {
            const prototype: {
            };

        }

        namespace listenerCount {
            const prototype: {
            };

        }

        namespace listeners {
            const prototype: {
            };

        }

        namespace log {
            const prototype: {
            };

        }

        namespace on {
            const prototype: {
            };

        }

        namespace once {
            const prototype: {
            };

        }

        namespace prependListener {
            const prototype: {
            };

        }

        namespace prependOnceListener {
            const prototype: {
            };

        }

        namespace profile {
            const prototype: {
            };

        }

        namespace prompt {
            const prototype: {
            };

        }

        namespace query {
            const prototype: {
            };

        }

        namespace rawListeners {
            const prototype: {
            };

        }

        namespace remove {
            const prototype: {
            };

        }

        namespace removeAllListeners {
            const prototype: {
            };

        }

        namespace removeListener {
            const prototype: {
            };

        }

        namespace setLevels {
            const prototype: {
            };

        }

        namespace setMaxListeners {
            const prototype: {
            };

        }

        namespace silly {
            const prototype: {
            };

        }

        namespace startTimer {
            const prototype: {
            };

        }

        namespace stream {
            const prototype: {
            };

        }

        namespace unhandleExceptions {
            const prototype: {
            };

        }

        namespace verbose {
            const prototype: {
            };

        }

        namespace warn {
            const prototype: {
            };

        }

    }

    export namespace on {
        const prototype: {
        };

    }

    export namespace once {
        const prototype: {
        };

    }

    export namespace pause {
        const prototype: {
        };

    }

    export namespace prependListener {
        const prototype: {
        };

    }

    export namespace prependOnceListener {
        const prototype: {
        };

    }

    export namespace rawListeners {
        const prototype: {
        };

    }

    export namespace removeAllListeners {
        const prototype: {
        };

    }

    export namespace removeListener {
        const prototype: {
        };

    }

    export namespace resume {
        const prototype: {
        };

    }

    export namespace setMaxListeners {
        const prototype: {
        };

    }

    export namespace start {
        const prototype: {
        };

    }

    export namespace stop {
        const prototype: {
        };

    }

}